version: '3'
services:

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/charlie/docker/homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host


  # homeassistant_backup:
  #   container_name: gdrivebackup
  #   environment:
  #     - FILE_PATH=/gdrivebackup
  #     - GDRIVE_FOLDER=Home Assistant Backups
  #     - BACKUPS_TO_KEEP=5
  #     - EMAIL_TO_SHARE=<<myemail>>
  #     - TZ=Europe/London
  #   volumes:
  #     - gdrivebackup_creds:/home/charlie/docker/homeassistant-backup/app/creds
  #     - /home/charlie/docker/homeassistant-config:/gdrivebackup
  #   image: "hassbackup:latest"

  portainer-ce:
    container_name: portainer
    environment:
      - TZ=Europe/London
    ports:
      - '8000:8000'
      - '9000:9000'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: "portainer/portainer-ce"


  mosquitto:
    container_name: mosquitto
    environment:
      - TZ=Europe/London
    ports:
      - '1883:1883'
      - '9001:9001'
    image: 'eclipse-mosquitto'
    volumes:
      - /home/charlie/docker/mosquitto/data:/mosquitto/data
      - /home/charlie/docker/mosquitto/log:/mosquitto/log
      - /home/charlie/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always


  zigbee2mqtt:
    container_name: zigbee2mqtt
    ports:
     - '8080:8080'
    depends_on:
      - mosquitto
    volumes:
      - '/home/charlie/ansible/zigbee2mqtt-data:/app/data'
      - '/run/udev:/run/udev:ro'
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/London
    privileged: true
    restart: always
    image: koenkk/zigbee2mqtt

  # budget:
  #   container_name: budget
  #   ports:
  #     - '5000:5000'
  #   environment:
  #     - BEANCOUNT_FILE=/budget_data/budget.beancount
  #     - TZ=Europe/London
  #   volumes:
  #     - '/home/charlie/sambashare/budget/budget:/budget_data'
  #   restart: always
  #   image: "budget:latest"
  

# version: "3"

# # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# services:
#   pihole:
#     container_name: pihole
#     image: pihole/pihole:latest
#     ports:
#       - "53:53/tcp"
#       - "53:53/udp"
#       - "67:67/udp"
#       - "80:80/tcp"
#     environment:
#       TZ: 'Europe/London'
#       WEBPASSWORD: 'password'
#     # Volumes store your data between container upgrades
#     volumes:
#       - './etc-pihole:/etc/pihole'
#       - './etc-dnsmasq.d:/etc/dnsmasq.d'
#     # Recommended but not required (DHCP needs NET_ADMIN)
#     #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#     cap_add:
#       - NET_ADMIN
#     restart: unless-stopped


volumes:
  portainer_data:
  gdrivebackup_creds: