- name: Install requirements
  hosts: ubuntu-rpi
  vars:
    
  vars_files:
    - secrets.yaml # to be inserted into templates
  tasks:

  # - name: Install boto3 # so we can use amazon aws
  #   become: yes
  #   ansible.builtin.pip:
  #     name: boto3


  - name: copy files to server
    copy:
      src: docker-compose.yml
      dest: /home/charlie/ansible/docker-compose.yml

  - name: copy zigbee2mqtt template
    template:
      src: zigbee2mqtt-data/configuration.yaml.j2
      dest: /home/charlie/ansible/zigbee2mqtt-data/configuration.yaml
