- name: Install influxdb
  hosts: ubuntu-rpi
  tasks:
  - name: Install InfluxDB packages
    become: yes
    apt: name=influxdb state=present

  - name: Modify InfluxDB hostname
    replace:
      dest=/etc/influxdb/influxdb.conf
      regexp='hostname = "localhost"'
      replace='hostname = "{{ ansible_hostname }}"'
      backup=yes

  - name: Start service influxdb, if not started
    become: yes
    ansible.builtin.service:
      name: influxdb
      state: restarted