{
 "title": "Finance",
 "time": { "from": "2019-12-18T16:07:16.935Z", "to": "2023-10-27T13:35:25.708Z" },
 "templating": {
  "list": [
   { "name": "bucket_name", "query": "finance" },
   { "name": "ma_months", "label": "Number of months for MA", "query": "12" }
  ]
 },
 "panels": [
  {
   "title": "Monthly expenses (${ma_months} month MA)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"${bucket_name}\")\n  |> filter(fn: (r) => r._field == \"relevant_expenses\")\n  |> movingAverage(n: ${ma_months})\n  |> yield()"
    }
   ]
  },
  {
   "title": "Savings rate  (${ma_months} month MA)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"${bucket_name}\")\n  |> filter(fn: (r) => r._field == \"saving_rate\")\n  |> movingAverage(n: ${ma_months})\n  |> yield()"
    }
   ]
  },
  {
   "title": "Net worth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"finance\" and (r.account =~ /Assets:*/) or (r.account =~ /Liabilities:*/))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"account\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: \n    r[\"Assets:BankAccounts:HSBC\"] +\n    r[\"Assets:BankAccounts:Monzo\"] +\n    r[\"Assets:BankAccounts:MarcusSavings\"] +\n    r[\"Assets:BankAccounts:CryptoCard\"] +\n    r[\"Assets:Investments:MoneyboxLISA\"] +\n    r[\"Assets:Investments:StocksSharesISA\"] +\n    r[\"Assets:Investments:Crypto\"] +\n    r[\"Liabilities:StudentLoan\"] +\n    r[\"Liabilities:Amex\"]\n\n     }))\n  |> drop(columns: [\n    \"Assets:BankAccounts:Monzo\",\n    \"Assets:BankAccounts:HSBC\",\n    \"Assets:BankAccounts:MarcusSavings\",\n    \"Assets:BankAccounts:CryptoCard\",\n    \"Assets:Investments:MoneyboxLISA\",\n    \"Assets:Investments:StocksSharesISA\",\n    \"Assets:Investments:Crypto\",\n    \"Liabilities:StudentLoan\",\n    \"Liabilities:Amex\"\n    ])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Student Loan",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"${bucket_name}\" and (r.account == \"Liabilities:StudentLoan\"))"
    }
   ]
  },
  {
   "title": "Net worth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"${bucket_name}\" and (r.account =~ /Assets:*/) or (r.account =~ /Liabilities:*/))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"account\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: \n    r[\"Assets:BankAccounts:HSBC\"] +\n    r[\"Assets:BankAccounts:Monzo\"] +\n    r[\"Assets:BankAccounts:MarcusSavings\"] +\n    r[\"Assets:BankAccounts:CryptoCard\"] +\n    r[\"Assets:Investments:MoneyboxLISA\"] +\n    r[\"Assets:Investments:StocksSharesISA\"] +\n    r[\"Assets:Investments:Crypto\"] +\n    r[\"Liabilities:StudentLoan\"] +\n    r[\"Liabilities:Amex\"]\n\n     }))\n  |> drop(columns: [\n    \"Assets:BankAccounts:Monzo\",\n    \"Assets:BankAccounts:HSBC\",\n    \"Assets:BankAccounts:MarcusSavings\",\n    \"Assets:BankAccounts:CryptoCard\",\n    \"Assets:Investments:MoneyboxLISA\",\n    \"Assets:Investments:StocksSharesISA\",\n    \"Assets:Investments:Crypto\",\n    \"Liabilities:StudentLoan\",\n    \"Liabilities:Amex\"\n    ])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Cash, investments, and liabilities",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"${bucket_name}\" and (r.account =~ /Assets:*/) or (r.account =~ /Liabilities:*/))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"account\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _liquid: \n    r[\"Assets:BankAccounts:HSBC\"] +\n    r[\"Assets:BankAccounts:Monzo\"] +\n    r[\"Assets:BankAccounts:MarcusSavings\"] +\n    r[\"Assets:BankAccounts:CryptoCard\"]\n     }))\n  |> map(fn: (r) => ({ r with _fixed: \n    r[\"Assets:Investments:StocksSharesISA\"] +\n    r[\"Assets:Investments:MoneyboxLISA\"] +\n    r[\"Assets:Investments:Crypto\"]\n     }))\n  |> map(fn: (r) => ({ r with _debt: \n    r[\"Liabilities:StudentLoan\"] +\n    r[\"Liabilities:Amex\"]\n     }))\n  |> drop(columns: [\n    \"Assets:BankAccounts:Monzo\",\n    \"Assets:BankAccounts:HSBC\",\n    \"Assets:BankAccounts:MarcusSavings\",\n    \"Assets:BankAccounts:CryptoCard\",\n    \"Assets:Investments:MoneyboxLISA\",\n    \"Assets:Investments:StocksSharesISA\",\n    \"Assets:Investments:Crypto\",\n    \"Liabilities:StudentLoan\",\n    \"Liabilities:Amex\"\n    ])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Change in Net Worth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"${bucket_name}\" and (r.account =~ /Assets:*/) or (r.account =~ /Liabilities:*/))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"account\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: \n    r[\"Assets:BankAccounts:HSBC\"] +\n    r[\"Assets:BankAccounts:Monzo\"] +\n    r[\"Assets:BankAccounts:MarcusSavings\"] +\n    r[\"Assets:BankAccounts:CryptoCard\"] +\n    r[\"Assets:Investments:MoneyboxLISA\"] +\n    r[\"Assets:Investments:StocksSharesISA\"] +\n    r[\"Assets:Investments:Crypto\"] +\n    r[\"Liabilities:StudentLoan\"] +\n    r[\"Liabilities:Amex\"]\n     }))\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> drop(columns: [\n    \"Assets:BankAccounts:Monzo\",\n    \"Assets:BankAccounts:HSBC\",\n    \"Assets:BankAccounts:MarcusSavings\",\n    \"Assets:BankAccounts:CryptoCard\",\n    \"Assets:Investments:MoneyboxLISA\",\n    \"Assets:Investments:StocksSharesISA\",\n    \"Assets:Investments:Crypto\",\n    \"Liabilities:StudentLoan\",\n    \"Liabilities:Amex\"\n    ])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Cash",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"${bucket_name}\" and (r.account =~ /Assets:BankAccounts:*/))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"account\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: \n    r[\"Assets:BankAccounts:HSBC\"] +\n    r[\"Assets:BankAccounts:Monzo\"] +\n    r[\"Assets:BankAccounts:MarcusSavings\"] +\n    r[\"Assets:BankAccounts:CryptoCard\"]\n     }))\n  |> drop(columns: [\n    \"Assets:BankAccounts:Monzo\",\n    \"Assets:BankAccounts:HSBC\",\n    \"Assets:BankAccounts:MarcusSavings\",\n    \"Assets:BankAccounts:CryptoCard\"\n    ])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Investments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "from(bucket: \"python\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"${bucket_name}\" and (r.account =~ /Assets:*/))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"account\"], valueColumn: \"_value\")\n  |> drop(columns: [\n    \"Assets:BankAccounts:Monzo\",\n    \"Assets:BankAccounts:HSBC\",\n    \"Assets:BankAccounts:MarcusSavings\",\n    \"Assets:BankAccounts:CryptoCard\",\n    ])\n  |> yield()"
    }
   ]
  }
 ]
}