version: "2.2"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false # to avoid creating passwords and needing to encrypt
      - discovery.type=single-node
    networks:
      - es-net

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.6.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
  
  # filebeat:
  #   container_name: filebeat
  #   user: root
  #   image: 'docker.elastic.co/beats/filebeat:8.6.1'
  #   environment:
  #     - setup.kibana.host=ubuntu-rpi:5601
  #     - output.elasticsearch.hosts=["elasticsearch-compose:9200"]
  #     - strict.perms=false
  #   volumes:
  #     - '/home/ansible-ssh/ansible/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro'
  #     - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
  #     - '/var/run/docker.sock:/var/run/docker.sock:ro'

networks:
  es-net:
