- name: Install Home Assistant update
  hosts: ubuntu-rpi
  vars:
    BUCKET_NAME: ubuntu-rpi-homeassistant-backups
  vars_files:
  - aws_secrets.yaml 
  tasks:

  - name: List keys simple
    amazon.aws.s3_object:
      bucket: "{{ BUCKET_NAME }}"
      mode: list
      access_key: "{{ AWS_ACCESS_KEY_ID }}"
      secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    register: output

  - ansible.builtin.debug:
      var: output
