- name: Backup home assistant config to S3
  hosts: ubuntu-rpi
  vars_files:
  - aws_secrets.yaml 
  tasks:

  - name: Compress homeassistant files
    become: yes
    community.general.archive:
      path: /home/charlie/docker/homeassistant-config
      dest: /home/charlie/docker/homeassistant-backup.tgz

  - name: Put the backup into S3
    become: yes 
    amazon.aws.s3_object:
      mode: put
      bucket: "{{ BUCKET_NAME }}"
      access_key: "{{ AWS_ACCESS_KEY_ID }}"
      secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      object: homeassistant-backup.tgz
      src: /home/charlie/docker/homeassistant-backup.tgz
    register: output

  - ansible.builtin.debug:
      var: output
