- name: Install requirements
  hosts: ubuntu-rpi
  vars:
    
  vars_files:
    - secrets.yaml # to be inserted into templates
  tasks:

  # - name: Install boto3 # so we can use amazon aws
  #   become: yes
  #   ansible.builtin.pip:
  #     name: boto3

  - name: Create directories if they do not already exist
    ansible.builtin.file:
      path: '/home/ansible-ssh/{{ item }}'
      state: directory
      mode: '0755'
    loop:
      - ansible
      - ansible/zigbee2mqtt-data
      - ansible/mosquitto
      - ansible/mosquitto/data
      - ansible/mosquitto/log
      - ansible/mosquitto/config

  - name: copy files to server
    copy:
      src: config-files/{{ item.src }}
      dest: /home/ansible-ssh/ansible/{{ item.dest }}
    loop:
      - { src: docker-compose.yml, dest: docker-compose.yml }
      - { src: mosquitto.conf, dest: mosquitto/config/mosquitto.conf }


  - name: copy zigbee2mqtt template
    template:
      src: config-files/configuration.yaml.j2
      dest: /home/ansible-ssh/ansible/zigbee2mqtt-data/configuration.yaml
