- name: Install requirements
  hosts: ubuntu-rpi
  vars:
    
  vars_files:
    - secrets.yaml # to be inserted into templates
  tasks:

  - name: install pip3
    become: yes
    apt: 
      name: python3-pip
      state: present 

  - name: Install pip packages
    become: yes
    ansible.builtin.pip:
      name: "{{ item }}"
    loop:
      - docker
      - docker-compose
      - boto3
  
  - name: Create directories if they do not already exist
    ansible.builtin.file:
      path: '/home/ansible-ssh/{{ item }}'
      state: directory
      mode: '0755'
    loop:
      - ansible
      - ansible/zigbee2mqtt-data
      - ansible/mosquitto
      - ansible/mosquitto/data
      - ansible/mosquitto/log
      - ansible/mosquitto/config

  - name: copy files to server
    copy:
      src: config-files/{{ item.src }}
      dest: /home/ansible-ssh/ansible/{{ item.dest }}
    loop:
      - { src: docker-compose.yml, dest: docker-compose.yml }
      - { src: mosquitto.conf, dest: mosquitto/config/mosquitto.conf }


  - name: copy zigbee2mqtt template
    template:
      src: config-files/configuration.yaml.j2
      dest: /home/ansible-ssh/ansible/zigbee2mqtt-data/configuration.yaml

  - name: Setup SSH rate limiting
    become: yes
    community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp

  - name: Allow all access to tcp ports
    become: yes
    community.general.ufw:
      rule: allow
      port: '{{ item }}'
      proto: tcp
    loop:
      - 8080 # zigbee2mqtt
      - 9000 # portainer
      - 1883 # mqtt
      - 8123 # homeassistant

  - name: Reload firewall
    become: yes
    community.general.ufw:
      state: reloaded