- name: Install Home Assistant update
  hosts: ubuntu-rpi
  tasks:

  - name: Tear down existing services
    become: yes
    community.docker.docker_compose:
      project_src: ansible
      state: absent # Specifying absent is the same as running docker-compose down

  - name: Pull an image
    become: yes
    community.docker.docker_image:
      name: ghcr.io/home-assistant/home-assistant:stable
      source: pull
      force_source: yes

  - name: Create and start services
    become: yes
    community.docker.docker_compose:
      project_src: ansible
      state: present # default is present
    register: output

  - ansible.builtin.debug:
      var: output
