version: '3'
services:

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/ansible-ssh/ansible/homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  portainer-ce:
    container_name: portainer
    environment:
      - TZ=Europe/London
    ports:
      - '8000:8000'
      - '9000:9000'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: "portainer/portainer-ce"


  mosquitto:
    container_name: mosquitto
    environment:
      - TZ=Europe/London
    ports:
      - '1883:1883'
      - '9001:9001'
    image: 'eclipse-mosquitto'
    volumes:
      - /home/ansible-ssh/ansible/mosquitto/data:/mosquitto/data
      - /home/ansible-ssh/ansible/mosquitto/log:/mosquitto/log
      - /home/ansible-ssh/ansible/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always


  zigbee2mqtt:
    container_name: zigbee2mqtt
    ports:
     - '8080:8080'
    depends_on:
      - mosquitto
    volumes:
      - '/home/ansible-ssh/ansible/zigbee2mqtt-data:/app/data'
      - '/run/udev:/run/udev:ro'
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/London
    privileged: true
    restart: always
    image: koenkk/zigbee2mqtt
  
  elasticsearch:
    container_name: elasticsearch-compose
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.9'
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: 'docker.elastic.co/kibana/kibana:7.17.9'
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch-compose:9200'
    ports:
      - '5601:5601'
    networks:
      - elastic


volumes:
  portainer_data:

networks:
  elastic: