version: '3'
services:

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/ansible-ssh/ansible/homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  portainer-ce:
    container_name: portainer
    environment:
      - TZ=Europe/London
    ports:
      - '8000:8000'
      - '9000:9000'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: "portainer/portainer-ce"


  mosquitto:
    container_name: mosquitto
    environment:
      - TZ=Europe/London
    ports:
      - '1883:1883'
      - '9001:9001'
    image: 'eclipse-mosquitto'
    volumes:
      - /home/ansible-ssh/ansible/mosquitto/data:/mosquitto/data
      - /home/ansible-ssh/ansible/mosquitto/log:/mosquitto/log
      - /home/ansible-ssh/ansible/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always


  zigbee2mqtt:
    container_name: zigbee2mqtt
    ports:
     - '8080:8080'
    depends_on:
      - mosquitto
    volumes:
      - '/home/ansible-ssh/ansible/zigbee2mqtt-data:/app/data'
      - '/run/udev:/run/udev:ro'
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/London
    privileged: true
    restart: always
    image: koenkk/zigbee2mqtt
  
  elasticsearch:
    container_name: elasticsearch-compose
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.9'
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elastic
    labels:
      - co.elastic.logs/module=elasticsearch

  kibana:
    container_name: kibana
    image: 'docker.elastic.co/kibana/kibana:7.17.9'
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch-compose:9200'
    ports:
      - '5601:5601'
    networks:
      - elastic
  
  logstash:
    container_name: logstash
    image: 'docker.elastic.co/logstash/logstash:8.6.1'
    volumes:
      - '/home/ansible-ssh/ansible/logstash/pipeline/:/usr/share/logstash/pipeline/' # logstash looks in /usr/share/logstash/pipeline/ by default for pipeline config
      #- /home/ansible-ssh/ansible/logstash/settings/:/usr/share/logstash/config/ # uncomment if you want to add settings, see https://www.elastic.co/guide/en/logstash/current/docker-config.html
  
  filebeat:
    container_name: filebeat
    user: root
    image: 'docker.elastic.co/beats/filebeat:8.6.1'
    environment:
      - setup.kibana.host=ubuntu-rpi:5601
      - output.elasticsearch.hosts=["elasticsearch-compose:9200"]
      - strict.perms=false
    volumes:
      - '/home/ansible-ssh/ansible/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'



volumes:
  portainer_data:

networks:
  elastic: